In [1]:
#Examples that follow the 2nd advanced python ppt (July 13th)

## Conditionals

In [ ]:
a = True
if a:
    print("The English word with the most definitions is \"set.\"")
    
b = False
if (b): #can use with or without parentheses
    print("Space smells like seared steak.")

In [ ]:
a = 11
if a == 10:
    print("The longest wedding veil was the same length as 63.5 football fields")
elif a == 11: #else if = elif
    print("The unicorn is the national animal of Scotland.")
else:
    print("\"E\" is the most common letter and appears in 11 percent of all english words.")

In [ ]:
#single line if statement:
print("hello") if 2>4 else print("bye")

In [ ]:
#using "and" & "or"
a = 27
b = True
if a>30 and b:
    print("Abraham Lincoln's bodyguard left his post at Ford's Theatre to go for a drink.")
    
if a>30 or b: 
    print("Dolphins have been trained to be used in wars.")

In [5]:
#Nested if statement
if a == 27:
    print("You have enough iron in your blood to create a nail.")
    if b == False:
        print("Redheads aren't actually going extinct.")
    elif b: 
        pass 
    else: #since b == True, the loop doesn't print our the kidney stone line
        print("Riding a roller coaster could help you pass a kidney stone.")
else:
    print("Sea lions can dance to a beat.")

You have enough iron in your blood to create a nail.


## Arrays, Lists, Dictionaries

In [12]:
#Lists
randomList = ["Scream", 12, 22.555, 'g']
print(randomList)

#add to list
randomList.append("The Shining")
print(randomList)

#accessing values
firstVal = randomList[0]
lastVal = randomList[4]
print("the first value of the list is ", firstVal, " and the last value is ", lastVal)

#length of the list
print(len(randomList))

['Scream', 12, 22.555, 'g']
['Scream', 12, 22.555, 'g', 'The Shining']
the first value of the list is  Scream  and the last value is  The Shining
5


In [23]:
import array as arr

#need to specify the type
newArray = arr.array([2, 43, 244, 43, 27, 9439])
newArray.append(54)
print(newArray)
newArray.append(33.2)
print(newArray)

TypeError: array() argument 1 must be a unicode character, not list

In [33]:
import numpy as np
npArray = np.array([45, "It Follows", 72.3, 88]) #can use multiple types
npArray2 = np.array([3, 6, 9, 12, 15])
print(npArray2/3)

[1. 2. 3. 4. 5.]


In [36]:
#more actions
#cannot edit length of numpy arrays once they are decleared, but the values can be edited
npArray[0] = "hereditary"
print(npArray)

#arange --- arange(finish) or arange(start, finish, space between)

array = np.arange(20)
print(array)
array2 = np.arange(10, 50, 5)
print(array2)

['hereditary' 'It Follows' '72.3' '88']
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[10 15 20 25 30 35 40 45]


In [43]:
#multiple dimensions
array2D = np.arange(27).reshape(3,3,3)
print(array2D)
print("\n shape:",array2D.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

 shape: (3, 3, 3)


In [53]:
#Quick Fill
print(np.zeros(10), "\n")

print(np.ones((2,4)), "\n")

print(np.empty((2,3)), "\n")

print(np.full((2,2), 44.3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[-2.31584178e+077 -1.29073615e-231  1.48219694e-323]
 [ 0.00000000e+000  0.00000000e+000  4.17201348e-309]] 

[[44.3 44.3]
 [44.3 44.3]]


Loops

In [57]:
#iterate over a list
primes = [2, 3, 5, 7]
for prime in primes:
    prime += 4
    print(prime)
    prime *= 2
    print(prime)

6
12
7
14
9
18
11
22


In [60]:
for x in range(5):
    print(x)
print("\n")

for x in range(3, 6):
    print(x)
print("\n")

for x in range(3, 8, 2):
    print(x)

0
1
2
3
4


3
4
5


3
5
7


In [61]:
#while *condition*
count = 0
while count < 5:
    print(count)
    count += 1  

0
1
2
3
4


In [63]:
#using break and continue
count = 0
while True:
    print(count)
    count += 1
    if count >= 5:
        break
print("\n")

# Prints out only odd numbers - 1,3,5,7,9
for x in range(10):
    # Check if x is even
    if x % 2 == 0:
        continue
    print(x)

0
1
2
3
4


1
3
5
7
9


In [66]:
#using "else" in for loops
count=0
while(count<5):
    print(count)
    count +=1
else:
    print("count value reached" %(count))

# Prints out 1,2,3,4
for i in range(1, 10):
    if(i%5==0):
        break
    print(i)
else:
    print("this is not printed because for loop is terminated because of break but not due to fail in condition")

0
1
2
3
4
count value reached 5
1
2
3
4


User and file interactions

In [ ]:
#user input
x = input("What is your favourite song? ")
print(x, "is a banger !!!!!!")

## File Intput/Output